framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: base/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        app: cache.adapter.redis
        default_redis_provider: snc_redis.cache

        # Namespaced pools use the above "app" backend by default
        # pools:
        #     base.cache:
        #         adapter: cache.adapter.redis
        #         provider: snc_redis.cache


