# modified version for docker-sync 0.4.*
# switch from :rw to :nocopy for all named volumes when using sync-strategy "native_osx" instead of "unison"
#
# check your version with $ docker-sync -v

version: "3"
services:
    web:
        image: nginx
        ports:
            - "8888:80"
            - "448:443"
        links:
            - php
            - "proxy:proxy.int.secrz.com"
        volumes:
            - ./docker-config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - WalterProjekt-sync:/var/www/html:nocopy
            - ./docker-config/nginx/localhost.crt:/etc/nginx/ssl/localhost.crt
            - ./docker-config/nginx/localhost.key:/etc/nginx/ssl/localhost.key

    php:
        build: ./docker-config/php
        links:
            - db
            - redis_master
            - "proxy:proxy.int.secrz.com"
        # pass variables with credentials for ldap-access and to prevent accidental commit of credentials
        environment:
            - CNTLM_DOMAIN
            - CNTLM_USERNAME
            - CNTLM_PASSWORD
            - LDAP_INT_PASSWORD
        volumes:
            - WalterProjekt-sync:/var/www/html:nocopy
            - ./docker-config/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker-config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf

    db:
        image: mariadb:10.3
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=rootpw
            - MYSQL_DATABASE=app
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./docker-config/mysql/mysql.cnf:/etc/mysql/conf.d/lidl.cnf
            - WalterProjekt-mysql-sync:/var/lib/mysql:nocopy

    redis_master:
        image: redis:4.0.14
        ports:
            - "6379:6379"
        volumes:
            - ./docker-config/redis:/data
        command: redis-server --appendonly yes --requirepass secret

#    redis-commander:
#        # redis commander interface: http://localhost:8081/
#        hostname: redis-commander
#        image: rediscommander/redis-commander:latest
#        links:
#            - redis_master
#        ports:
#            - "8088:8081"
#        environment:
#            REDIS_PASSWORD: secret
#            REDIS_HOST: redis_master
#            REDIS_PORT: 6379
#            REDIS_DB: 8
#            REDIS_HOSTS: "master:redis_master:6379:8"

    proxy:
        image: bachp/cntlm
        environment:
            - CNTLM_PROXY
            - CNTLM_USERNAME
            - CNTLM_PASSWORD
            - CNTLM_DOMAIN

volumes:
    WalterProjekt-sync:
        external: true
    WalterProjekt-mysql-sync:
