version: '3'

networks:
  nginx-php74-mysql8-node:

services:

    #nginx
    nginx-services:
      image: nginx:stable-alpine
      container_name: nginx-container
      ports:
      - "8080:80"
      volumes:
        - ./app:var/www/project
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php74-service
        - mysql8-service
      networks:
        - nginx-php74-mysql8-node
    #php
    php74-service:
    
    #mysql
    mysql8-service:

    #node
    node-service:

