monolog:
    channels: ['main', 'authentication', 'logme_service']

    handlers:
        main:
            level:      debug
            type:       rotating_file
            max_files:  10
            formatter:  'Monolog\Formatter\JsonFormatter'
            path:       "%kernel.logs_dir%/%kernel.environment%.log"
            channels:   ["!event"]

        # log all activity related to the guard ldap authenticator and application access
        authentication:
            level:      debug
            type:       rotating_file
            max_files:  10
            path:       '%kernel.logs_dir%/authentication-%kernel.environment%.log'
            formatter:  monolog.formatter.authentication_request
            channels:   ['authentication']

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

        # log all messages to logme service of cloudfoundry
        logme_service:
            type: stream
            formatter: 'Monolog\Formatter\JsonFormatter'
            level: debug
            path: "php://stdout"
            channels: [ "!event", "!doctrine", "!console"]

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info