monolog:
    channels: ['main', 'authentication', 'logme_service']

    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/

        # log all activity related to the guard ldap authenticator and application access
        authentication:
            level: debug
            type: rotating_file
            max_files: 10
            path: '%kernel.logs_dir%/authentication-%kernel.environment%.log'
            formatter: monolog.formatter.authentication_request
            channels: [ 'authentication' ]

        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug

        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']

        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ['php']

        # log all messages to logme service of cloudfoundry
        logme_service:
            type: stream
            formatter: 'Monolog\Formatter\JsonFormatter'
            level: debug
            path: "php://stdout"