<?php

return [
    '@DoctrineAnnotation' => true,
    '@PHPUnit75Migration:risky' => true,
    '@Symfony' => true,
    'align_multiline_comment' => [
        'comment_type' => 'all_multiline',
    ],
    'array_indentation' => true,
    'array_syntax' => [
        'syntax' => 'short',
    ],
    'backtick_to_shell_exec' => true,
    'blank_line_before_statement' => [
        'statements' => [
            'break',
            'continue',
            'declare',
            'do',
            'for',
            'foreach',
            'if',
            'include',
            'include_once',
            'require',
            'require_once',
            'return',
            'switch',
            'throw',
            'try',
            'while',
            'yield',
        ],
    ],
    'class_attributes_separation' => [
        'elements' => [
            'method',
        ],
    ],
    'combine_consecutive_issets' => true,
    'combine_consecutive_unsets' => true,
    'combine_nested_dirname' => true,
    'comment_to_phpdoc' => true,
    'compact_nullable_typehint' => true,
    'concat_space' => [
        'spacing' => 'one',
    ],
    'declare_equal_normalize' => [
        'space' => 'single',
    ],
    'dir_constant' => true,
    'ereg_to_preg' => true,
    'explicit_indirect_variable' => true,
    'explicit_string_variable' => true,
    'final_static_access' => true,
    'fopen_flag_order' => true,
    'fully_qualified_strict_types' => true,
    'function_to_constant' => true,
    'hash_to_slash_comment' => true,
    'header_comment' => [
        'header' => '',
    ],
    'implode_call' => true,
    'is_null' => true,
    'linebreak_after_opening_tag' => true,
    'list_syntax' => [
        'syntax' => 'short',
    ],
    'logical_operators' => true,
    'modernize_types_casting' => true,
    'multiline_comment_opening_closing' => true,
    'multiline_whitespace_before_semicolons' => [
        'strategy' => 'no_multi_line',
    ],
    'native_function_invocation' => true,
    'no_alias_functions' => true,
    'no_alternative_syntax' => true,
    'no_binary_string' => true,
    'no_extra_blank_lines' => [
        'tokens' => [
            'break',
            'case',
            'continue',
            'curly_brace_block',
            'default',
            'extra',
            'parenthesis_brace_block',
            'return',
            'square_brace_block',
            'switch',
            'throw',
            'use',
            'use_trait',
        ],
    ],
    'no_homoglyph_names' => true,
    'no_mixed_echo_print' => [
        'use' => 'echo',
    ],
    'no_null_property_initialization' => true,
    'no_short_echo_tag' => true,
    'no_superfluous_elseif' => true,
    'no_superfluous_phpdoc_tags' => true,
    'no_unreachable_default_argument_value' => true,
    'no_unset_cast' => true,
    'no_useless_else' => true,
    'no_useless_return' => true,
    'non_printable_character' => true,
    'nullable_type_declaration_for_default_null_value' => true,
    'ordered_class_elements' => true,
    'ordered_imports' => true,
    'ordered_interfaces' => [
        'direction' => 'ascend',
        'order' => 'alpha',
    ],
    'phpdoc_line_span' => [
        'const' => 'multi',
        'method' => 'multi',
        'property' => 'multi',
    ],
    'phpdoc_types_order' => [
        'null_adjustment' => 'always_last',
        'sort_algorithm' => 'alpha',
    ],
    'php_unit_construct' => true,
    'php_unit_method_casing' => true,
    'php_unit_mock_short_will_return' => true,
    'php_unit_ordered_covers' => true,
    'php_unit_set_up_tear_down_visibility' => true,
    'php_unit_test_annotation' => [
        'style' => 'prefix',
    ],
    'php_unit_test_case_static_method_calls' => [
        'call_type' => 'self',
    ],
    'phpdoc_order' => true,
    'phpdoc_to_comment' => false,
    'phpdoc_trim_consecutive_blank_line_separation' => true,
    'phpdoc_var_annotation_correct_order' => true,
    'pow_to_exponentiation' => true,
    'protected_to_private' => true,
    'psr4' => true,
    'return_assignment' => true,
    'self_accessor' => true,
    'self_static_accessor' => true,
    'set_type_to_cast' => true,
    'simple_to_complex_string_variable' => true,
    'single_line_throw' => false,
    'string_line_ending' => true,
    'ternary_to_null_coalescing' => true,
    'visibility_required' => [
        'elements' => [
            'const',
            'method',
            'property',
        ],
    ],
    'void_return' => true,
];
